#!/usr/bin/env python3
"""Persist same-run production and shadow snapshots as one validated batch."""

from __future__ import annotations

import argparse
import json
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path: sys.path.insert(0, str(ROOT))

from modeling.src.prospective import ProspectiveLedger


def persist_batch(path: Path, rows: list[dict], expected_versions: set[str] | None = None) -> list[str]:
    if not rows:
        return []
    timestamps = {row["generated_at"] for row in rows}
    if len(timestamps) != 1:
        raise ValueError("production and shadow snapshots must share one pipeline timestamp")
    by_match: dict[str, set[str]] = {}
    for row in rows:
        by_match.setdefault(str(row["match_id"]), set()).add(row["model_version"])
    if any(len(versions) < 2 for versions in by_match.values()):
        raise ValueError("each match requires both production and shadow model versions")
    if expected_versions is not None and any(versions != expected_versions for versions in by_match.values()):
        raise ValueError("each match must contain the exact production and shadow versions")
    ledger = ProspectiveLedger(path)
    return [ledger.persist(row) for row in rows]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("batch", type=Path, help="JSON list generated by the scheduled production/shadow prediction step")
    parser.add_argument("--dry-run", action="store_true", help="validate using a temporary ledger without changing the prospective ledger")
    parser.add_argument("--production-version", default="elo-context-v4.2.1")
    parser.add_argument("--shadow-version", default="elo-context-v4.4-opponent-adjusted-xg-experimental")
    args = parser.parse_args()
    rows = json.loads(args.batch.read_text())
    expected={args.production_version,args.shadow_version}
    if args.dry_run:
        with tempfile.TemporaryDirectory() as directory:
            digests=persist_batch(Path(directory)/"ledger.json",rows,expected)
        print(json.dumps({"status":"valid","snapshots":len(digests),"ledger_mutated":False}))
        return
    print(json.dumps(persist_batch(ROOT / "data/evaluation/wc26_prospective_predictions.json", rows, expected)))


if __name__ == "__main__": main()
